using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OOP05Demo.Partial
{
    //Imagine Auto generated by EF
    partial class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public int? Age {  get; set; }

        // Partial method => 
        // 1. no Access modifier
        // 2. only return void 
        // 3. does not allow passing by out
        partial void Print();

    }
}
